resources:
  - name: git-master
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/tech-docs-monitor
      branch: master
  - name: schedule
    type: time
    icon: clock-outline
    source:
      start: 12:05
      stop: 13:05
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]
      location: Europe/London

jobs:
  - name: update-pipeline
    plan:
      - get: git-master
        trigger: true
      - set_pipeline: daniel-the-manual-spaniel
        file: git-master/pipeline.yml

  - name: daniel-the-manual-spaniel
    serial: true
    plan:
      - get: schedule
        trigger: true
      - get: git-master
      - task: "notify:expired"
        timeout: 90m
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ruby
              tag: 2.7.5
              username: ((docker_hub_username))
              password: ((docker_hub_authtoken))
          inputs:
            - name: git-master
          params:
            REALLY_POST_TO_SLACK: 1
            SLACK_WEBHOOK_URL: https://((tech_docs_monitor_slack_webhook_url))
          run:
            dir: git-master
            path: bash
            args:
              - -c
              - |
                bundle install
                bundle exec rake notify:expired
